logging:
  level: INFO
  loggers:
    tech.form3: DEBUG

server:
  adminContextPath: /
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 8090
  adminConnectors:
    - type: http
      port: 8091

hostUrl: https://api.test.form3.tech